# Generated by Django 4.1.7 on 2023-10-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_timestamp_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_users', to='auctions.auctionlisting'),
        ),
    ]
